# Generated by Django 4.2.2 on 2023-06-12 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='tgl_mulai',
            field=models.DateField(),
        ),
    ]
