# Generated by Django 4.2.2 on 2023-06-12 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_order_tgl_mulai'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Out for delivery', 'Out for delivery'), ('Delivered', 'Delivered')], default=('Pending', 'Pending'), max_length=200, null=True),
        ),
    ]
